[build]
builder = "nixpacks"
buildCommand = "cd apps/studio && pnpm install && SKIP_UPLOAD_STATIC_ASSETS=true pnpm build"

[deploy]
startCommand = "cd apps/studio && pnpm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 